# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw2_part2/hw2_part2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2 || ORIG_REF_NAME==hw2_part2} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_axi_uartlite_0_0/hw2_part2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_axi_uartlite_0_0 || ORIG_REF_NAME==hw2_part2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_clk_wiz_0_0/hw2_part2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_clk_wiz_0_0 || ORIG_REF_NAME==hw2_part2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_mdm_1_0/hw2_part2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_mdm_1_0 || ORIG_REF_NAME==hw2_part2_mdm_1_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_microblaze_0_0/hw2_part2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_microblaze_0_0 || ORIG_REF_NAME==hw2_part2_microblaze_0_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_microblaze_0_axi_periph_0/hw2_part2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hw2_part2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_dlmb_v10_0/hw2_part2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_dlmb_v10_0 || ORIG_REF_NAME==hw2_part2_dlmb_v10_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_ilmb_v10_0/hw2_part2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_ilmb_v10_0 || ORIG_REF_NAME==hw2_part2_ilmb_v10_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_dlmb_bram_if_cntlr_0/hw2_part2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hw2_part2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_ilmb_bram_if_cntlr_0/hw2_part2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hw2_part2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_lmb_bram_0/hw2_part2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_lmb_bram_0 || ORIG_REF_NAME==hw2_part2_lmb_bram_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_rst_clk_wiz_0_100M_0/hw2_part2_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==hw2_part2_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_xbar_0/hw2_part2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_xbar_0 || ORIG_REF_NAME==hw2_part2_xbar_0} -quiet] -quiet

# IP: bd/hw2_part2/ip/hw2_part2_RSA_0_0/hw2_part2_RSA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part2_RSA_0_0 || ORIG_REF_NAME==hw2_part2_RSA_0_0} -quiet] -quiet

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2Vivado/HW2/HW2.gen/sources_1/bd/hw2_part2/hw2_part2_ooc.xdc
