# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/hw2_part1/hw2_part1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1 || ORIG_REF_NAME==hw2_part1} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_dlmb_bram_if_cntlr_0/hw2_part1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hw2_part1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_dlmb_v10_0/hw2_part1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_dlmb_v10_0 || ORIG_REF_NAME==hw2_part1_dlmb_v10_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_ilmb_bram_if_cntlr_0/hw2_part1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hw2_part1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_ilmb_v10_0/hw2_part1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_ilmb_v10_0 || ORIG_REF_NAME==hw2_part1_ilmb_v10_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_lmb_bram_0/hw2_part1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_lmb_bram_0 || ORIG_REF_NAME==hw2_part1_lmb_bram_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_axi_uartlite_0_0/hw2_part1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_axi_uartlite_0_0 || ORIG_REF_NAME==hw2_part1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_clk_wiz_0_0/hw2_part1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_clk_wiz_0_0 || ORIG_REF_NAME==hw2_part1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_mdm_1_0/hw2_part1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_mdm_1_0 || ORIG_REF_NAME==hw2_part1_mdm_1_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_microblaze_0_0 || ORIG_REF_NAME==hw2_part1_microblaze_0_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_microblaze_0_axi_periph_0/hw2_part1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hw2_part1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw2_part1/ip/hw2_part1_rst_clk_wiz_0_100M_0/hw2_part1_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw2_part1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==hw2_part1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.gen/sources_1/bd/hw2_part1/hw2_part1_ooc.xdc
