# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.srcs/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0.xci
# IP: The module: 'hw2_part1_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.gen/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.gen/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.gen/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.srcs/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0.xci
# IP: The module: 'hw2_part1_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.gen/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.gen/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2_part1/HW2_part1.gen/sources_1/bd/hw2_part1/ip/hw2_part1_microblaze_0_0/hw2_part1_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
