# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2Vivado/HW2/HW2.srcs/sources_1/bd/hw2_part2/ip/hw2_part2_xbar_0/hw2_part2_xbar_0.xci
# IP: The module: 'hw2_part2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2Vivado/HW2/HW2.gen/sources_1/bd/hw2_part2/ip/hw2_part2_xbar_0/hw2_part2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part2_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2Vivado/HW2/HW2.srcs/sources_1/bd/hw2_part2/ip/hw2_part2_xbar_0/hw2_part2_xbar_0.xci
# IP: The module: 'hw2_part2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mvbos/Desktop/SoC/SoC_Design/HW2/HW2Vivado/HW2/HW2.gen/sources_1/bd/hw2_part2/ip/hw2_part2_xbar_0/hw2_part2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw2_part2_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
